---
title: "Calculating degree of polarisation"
# author: "Laura Ospina-Rozo"
# date: "25/04/2022"
editor_options: 
  chunk_output_type: console
---

Absorptivity

# load data

```{r}
Cons2 <- read.csv("../Data/FromCode/ConsolidatedAbsoptivityInd.csv")[-1]

Cons2 <- 
  Cons2 %>% 
  arrange(ind)

```

```{r}
SppNames <- read.csv("../Data/9_CodesAndSpecies.csv")

SppNames <-
  SppNames %>% 
  mutate (spp = substr(Ind, 1, 4)) %>% 
  filter (spp != "ambl"& # Amblyterus cicatricosus
          spp != "psqz"& # Pseudoschizongnatus schoenfeldti
          spp != "saul"& # Saulostomus villosus
          spp != "sqzb"& # Schizognathus burmeisteri
          spp != "sqzc"& # Schizognathus compressicornis
          spp != "sqzm"  # Schizognathus mesosternalis
            ) %>% # These species were removed. No phylogenetic info
  dplyr::select (-spp) %>% 
  arrange(Ind)

SppNamesSub <- SppNames[SppNames$Ind %in% Cons2$ind,]

ConsAb<-data.frame(Cons2, SppNamesSub)

ConsAbSpp <-
  ConsAb %>% 
  select(-ind, - Ind) %>% 
  select(size, A_ALL, A_VIS, A_NIR, phylogeny_name) %>% 
  group_by(phylogeny_name) %>% 
  dplyr::summarise (across(everything(), list(mean))) # mean
  
head(ConsAbSpp)

```


Phylogeny (multiple trees)

```{r}
trees <- ape::read.tree("../Data/XMAS_mat2b_bst2ef_set23nn2_pinct.nwk")

MCCtree <- 
  ape::read.nexus("../Data/xmas_mat2b_bst2ef_set23nn2_pinct_med.tre")
MCCtree.raw <- 
  ape::read.nexus("../Data/xmas_mat2b_bst2ef_set23nn2_pinct_med.tre")
```

```{r}
# Prune extra spp in the tree, not contain in the test sample
species.MCCAb <- as.data.frame(unique(ConsAbSpp$phylogeny_name))
# Convert to "row names" (required for following steps)
row.names(species.MCCAb) <- species.MCCAb[, 1]
# Make sure the names in data set and tree match
temp.MCCAb <- name.check(MCCtree.raw, species.MCCAb)
temp.MCCAb 


MCCtreeAb <- drop.tip(MCCtree.raw, temp.MCCAb$tree_not_data)

```


Make comparative data subset

```{r}
comp_dataAb <- comparative.data(
  phy = MCCtreeAb,
   data = ConsAbSpp, # aggregated data without the spp in the row names
   names.col = "phylogeny_name", # contains the column phylogeny name
   vcv = TRUE,
   na.omit = FALSE, warn.dropped = TRUE)
```


```{r}
pglsPDVISAb <- pgls(VIS ~ Pol,
   data = comp_data_Ab, param.CI = 0.95, lambda = "ML"
 )
 
summary(pglsPDVISAb)
```

##########################################FINISH this!!!

Test Relations
Lower PC1 is higher max and min temp, higher humidity (vapour and rain)

Models

```{r}
EcoMod_Abs_TOT <- lm( data = Cons2, A_ALL ~ PC1 + PC2 + size)

EcoMod_Abs_VIS <- lm( data = Cons2, A_VIS ~ PC1 + PC2 + size)

EcoMod_Abs_NIR <- lm( data = Cons2, A_NIR ~ PC1 + PC2 + size)

export_summs(EcoMod_Abs_TOT, EcoMod_Abs_VIS, EcoMod_Abs_NIR, 
             error_format = "SE = {std.error} p = {p.value}",
             model.names = c("TOT", "VIS", "NIR")) 
```

Neither PC’s, nor size can explain the absorptivity in this subset of data with a linear relation.

Plot PC1

```{r}
toplotAPC1 <- 
  Cons2 %>% 
  dplyr::select (1, 2, 4, 11, 12, 13) %>% 
  gather (key = spectralband, 
          value = Absorptivity, - ind, -PC1, -size)   # prepare for ggplot


ggplot(toplotAPC1, aes(x = PC1, y = Absorptivity, colour = spectralband))+
  geom_point(size=2,alpha=0.4)+
  geom_point(size=2, pch=21, colour="black", alpha=0.7)+
  theme_bw()+
  facet_wrap(~ spectralband) +
  scale_color_brewer(palette = "Accent")+
  theme(legend.position = "none")

```

To plot PC2

```{r}
toplotAPC2 <- 
  Cons2 %>% 
  dplyr::select (1, 3, 4, 11, 12, 13) %>% 
  gather (key = spectralband, 
          value = Absorptivity, - ind, -PC2, -size)   # prepare for ggplot

ggplot(toplotAPC2, aes(x = PC2, y = Absorptivity, colour = spectralband))+
  geom_point(size=2,alpha=0.4)+
  geom_point(size=2, pch=21, colour="black", alpha=0.7)+
  geom_text(data = subset (toplotAPC2, PC2 < -1.5), 
            aes(label=ind),col="black",
            position = position_nudge(x = -0.5, y= 3),
            alpha=.3, size=1.5)+
  ylim(-10,100)+
  xlim(-9,3)+
  theme_bw()+
  facet_wrap(~ spectralband) +
  scale_color_brewer(palette = "Accent")+
  theme(legend.position = "none")
```

