---
output:
  html_document:
      toc: no
---

# Photonic rebels: Christmas beetle’s reflectivity, absorptivity, and polarisation do not follow one universal ecogeographical rule 

<br>

```{r warning=FALSE, message=FALSE}
library(imager)
im<-load.image(here::here("Data/RmdImages/ChapterCoverImage.png"))
plot(im, axes = FALSE)

```

<br>

<span style="color: #04C799"> **Introduction** </span>  <br/>
Welcome to this interactive code version!

In support of the Open Science framework, we provide an interactive HTML version of our code with the calculations and packages we used to derive our conclusions. All our code was written in R programming language and then converted into a GitHub page. Find the original data and permanent version tracking of the code here: https://github.com/lospinarozo/PhotonicRebelsCode.

Authors have been removed to facilitate double blind review.

<br>
<br>

<span style="color: #04C799"> **Brief table of contents** </span>  <br/>

These are the main resources:

- Preliminary steps

  -- [Studied species](https://lospinarozo.github.io/PhotonicRebelsCode/MacroEcol_1_SettingUp.html)

  -- [Processing of spectral measurements](https://lospinarozo.github.io/PhotonicRebelsCode/MacroEcol_2_OpticalProperties.html)

  -- [Calculation of the degree of polarisation](https://lospinarozo.github.io/PhotonicRebelsCode/MacroEcol_3_Polarisation.html)

  -- [Humidity and temperature (PCA)](https://lospinarozo.github.io/PhotonicRebelsCode/MacroEcol_4_EcologicalVariables.html)

- Results

  -- [Optical properties in the MCC tree](https://lospinarozo.github.io/PhotonicRebelsCode/MacroEcol_11_ExtraFigures.html)
  
  -- [Large beetles in dry environments](https://lospinarozo.github.io/PhotonicRebelsCode/MacroEcol_8_SizeStats.html)
  
  -- [Reflectivity in small and large beetles](https://lospinarozo.github.io/PhotonicRebelsCode/MacroEcol_5_ReflectivityStats.html)
  
  -- [NIR reflectivity reduced by chiral structures](https://lospinarozo.github.io/PhotonicRebelsCode/MacroEcol_7_PolarisationStats.html#Degree_of_polarisation)
  
  -- [Visible reflectivity reduced by "pigments"](https://lospinarozo.github.io/PhotonicRebelsCode/MacroEcol_7_PolarisationStats.html#Right_handed_polarisation)
  
  -- Note: We repeated all the analysis excluding _A. prasinus_ and the species belonging to the genus Xylonichus, Paraschizognathus as a way to test if our large-scale patterns where driven by extreme values. Results in the tabs label "Subset". Unlike many scarabs, these species are known to have a bilayered mechanism that is not chiral and enhances NIR reflectivity (Ospina-Rozo et al. 2023 Deconstructed Beetles).